# Clase 1 de la unidad 2

## Series y DataFrames desde cero

Este cuaderno acompaña la clase interactiva Analítica de datos 2.0. Primero revisa los fundamentos del aula de introducción a Python. La secuencia recomendada y la guía docente están en el sitio.

Cada fila del conjunto simulado corresponde a un lote de 60 minutos programados. Los ejemplos utilizan ocho registros y diez campos. Antes de ejecutar cada celda, predice el resultado y explica después lo que observas.

Ejecuta de arriba abajo con Mayús más Intro. Guardar el cuaderno conserva su contenido. Reiniciar el núcleo borra las variables y exige volver a ejecutar la preparación.

## Archivo del caso

La celda siguiente usa Path, de la biblioteca estándar de Python. Comprueba si produccion.csv ya existe en la carpeta actual. Si falta, crea una copia con los datos del ejercicio; si existe, lo conserva. No modifica un archivo que ya tengas guardado. La triple comilla delimita un texto de varias líneas. La sangría bajo if indica qué se ejecuta cuando falta el archivo.

In [1]:
from pathlib import Path
archivo = Path("produccion.csv")
if not archivo.exists():
    archivo.write_text('id,fecha,producto,linea,turno,cantidad,defectuosas,tiempo_min,parada_min,costo\n1,2026-09-01,P1,L1,A,100,2,60,22.5,70000\n2,2026-09-02,P1,L1,B,90,3,60,28.5,65000\n3,2026-09-03,P1,L1,A,110,4,60,19.5,75000\n4,2026-09-04,P1,L1,B,100,5,60,22.5,70000\n5,2026-09-05,P1,L1,A,120,2,60,13.5,80000\n6,2026-09-06,P1,L1,B,110,3,60,19.5,75000\n7,2026-09-07,P1,L1,A,130,4,60,7.5,85000\n8,2026-09-08,P1,L1,B,120,5,60,13.5,80000\n', encoding="utf-8")
print("Archivo del caso disponible:", archivo.name)

Archivo del caso disponible: produccion.csv

## Una tabla de producción, una pregunta a la vez

Aprende a leer y consultar datos con pandas, desde la primera fila hasta un filtro explicado con tus propias palabras.

Propósito: Al terminar podrás cargar ocho lotes de producción, revisar qué contienen y seleccionar los registros que responden una pregunta concreta.

<p>La jefatura de Taller Andino recibe registros de producción y pide una revisión inicial. Antes de proponer cambios, necesitas saber qué representa cada fila, cómo están escritos los datos y qué registros puedes consultar.</p><p>Los datos de esta clase son simulados. Cada fila es un lote distinto de un mismo producto en la línea L1, con 60 minutos programados. La cantidad incluye las unidades defectuosas. Las paradas ocurren dentro de esos 60 minutos.</p><h2>El orden recomendado de estudio</h2><p>La clase que ya existe de <a href="https://karendayana2590-bot.github.io/1682913-ANAL-TICA-DE-DATOS/" target="_blank" rel="noopener">Introducción a Python para analítica de datos</a> va primero en sus fundamentos. Revisa el entorno, las variables, las listas y los diccionarios, y cómo se importa una biblioteca. Sus bloques posteriores de NumPy, pandas y proyecto industrial pueden retomarse después como ampliación.</p><p>Esta clase concentra el estudio en Series y DataFrames. Todavía no necesitas dominar funciones propias, ciclos, estadística ni SQL. Si un signo te resulta desconocido, el tramo «Leer una instrucción» te permite practicarlo aquí.</p><h2>Cómo usar esta clase</h2><ol><li>Lee la pregunta y anticipa qué información necesitas.</li><li>Explora el ejemplo visual antes de mirar el código.</li><li>Lee la explicación de cada línea y ejecuta una instrucción.</li><li>Cambia una sola parte y explica el resultado.</li><li>Responde la comprobación y resuelve el reto con otra pregunta.</li></ol><div class="notice"><strong>Dos formas de practicar</strong><p>El explorador visual responde de inmediato y funciona sin descargar Python. El laboratorio ejecuta Python y pandas reales en tu navegador cuando lo activas; la primera carga necesita Internet. Los dos espacios están identificados para que sepas qué estás utilizando.</p></div><h2>Qué conservarás al terminar</h2><p>La tabla consultada, tus respuestas y una decisión inicial. «Guardar mi trabajo» descarga un registro de tus actividades y del código que escribiste. El avance guardado representa los tramos que tú revisaste, no una certificación de dominio.</p>

### Comprobación

Una fila del caso representa…

- Una unidad defectuosa
- Un lote distinto de 60 minutos programados
- La producción de toda la empresa durante un año

<details><summary>Respuesta y razón</summary><p>Un lote distinto de 60 minutos programados. Cada registro reúne información de un lote. Hay ocho lotes, con cantidades diferentes. No confundas número de registros con número de unidades.</p></details>

## Cada fila tiene una historia y cada columna una variable

Una cantidad como 100 necesita contexto: qué se produjo, en qué lote y durante cuánto tiempo.

Propósito: Reconocer un dato, una variable y un registro sin confundir el id del lote con la cantidad producida.

<p>Un <strong>dato</strong> es una observación registrada. En la primera fila, 100 es el valor observado de cantidad y A es el valor observado de turno. La <strong>variable</strong> es la característica que observamos: cantidad o turno.</p><p>Una <strong>columna</strong> reúne los valores de una misma variable. Una <strong>fila</strong> reúne las características de un registro. Aquí registro y lote describen la misma unidad de observación. Una <strong>tabla</strong> organiza esos registros en columnas con nombres.</p><p>Selecciona el encabezado <strong>cantidad</strong> para reconocer una columna. Después selecciona la fila del id 3 y explica qué sabes de ese lote.</p>

Los diez campos son id, fecha, producto, linea, turno, cantidad, defectuosas, tiempo_min, parada_min y costo. El índice dibujado por pandas no añade un campo al CSV.

<h2>Qué significa cada campo</h2><div class="table-wrap"><table class="dictionary"><thead><tr><th>Campo</th><th>Significado</th></tr></thead><tbody><tr><td>id</td><td>Identificador del lote. Distingue registros y debe ser único.</td></tr><tr><td>fecha</td><td>Día de producción, escrito como año-mes-día.</td></tr><tr><td>producto</td><td>Código del producto. P1 en estos ocho lotes.</td></tr><tr><td>linea</td><td>Línea de fabricación. L1 en el caso.</td></tr><tr><td>turno</td><td>Categoría del turno: A o B.</td></tr><tr><td>cantidad</td><td>Unidades totales producidas en el lote.</td></tr><tr><td>defectuosas</td><td>Unidades incluidas en cantidad que presentan defectos.</td></tr><tr><td>tiempo_min</td><td>Minutos programados del lote: 60.</td></tr><tr><td>parada_min</td><td>Minutos de parada incluidos dentro del tiempo programado.</td></tr><tr><td>costo</td><td>Costo total del lote en pesos colombianos.</td></tr></tbody></table></div><p><strong>Lectura del id 3:</strong> el 3 de septiembre, el turno A registró 110 unidades de P1 en L1, con cuatro defectuosas. La fila tiene 60 minutos programados y 19.5 de parada. Ese id no significa que se hayan producido tres unidades.</p><p>La tabla todavía no contiene ventas ni demanda. Una inspección correcta también permite reconocer qué preguntas no pueden responderse con los campos disponibles.</p>

### Comprobación

¿Cuántas columnas de datos tiene el archivo?

- Ocho, porque hay ocho lotes
- Diez, porque hay diez campos con nombre
- Once, contando el índice visual de pandas

<details><summary>Respuesta y razón</summary><p>Diez, porque hay diez campos con nombre. El archivo tiene diez campos. Cuando pandas dibuje un índice a la izquierda, ese índice no agregará una columna al CSV.</p></details>

## Los signos también se leen

Comprender una instrucción corta evita copiar símbolos sin saber qué hacen.

Propósito: Distinguir asignación, comparación, texto, selección y ejecución de una operación.

<p>Una <strong>variable de Python</strong> es un nombre que permite volver a utilizar un objeto. En <code>cantidad = 100</code>, el nombre cantidad queda asociado al número 100. Escribir <code>cantidad == 100</code> pregunta si su valor es igual a 100.</p><p>El texto se escribe entre comillas rectas, por ejemplo <code>"A"</code>. El número <code>100</code> se escribe sin comillas cuando lo usamos como cantidad numérica. Python distingue mayúsculas de minúsculas: <code>df</code> y <code>DF</code> son nombres diferentes.</p><h2>Desarma esta instrucción</h2><pre class="code-display"><code>df["cantidad"].head(3)</code></pre><p>Selecciona cada parte para leer su significado. No necesitas memorizarla completa en este momento.</p>

### Comprobar que asignar y comparar son operaciones distintas.

El ejemplo empieza sin variables preparadas.

In [2]:
cantidad = 100
print(cantidad == 100)

True

**Qué hace cada línea**

1. cantidad = 100 guarda el número con ese nombre.

2. print muestra el resultado de la comparación. == pregunta si los dos valores son iguales.

**Resultado esperado:** True

**Interpretación:** La comparación es verdadera. True y False son valores booleanos, útiles para decidir qué registros cumplen una condición.

**Error y corrección:** Si escribes = dentro de una comparación, puedes provocar un error de sintaxis. Usa comillas rectas para textos.

**Decisión:** Reconocer qué condición debe cumplir un registro antes de filtrarlo.

<h2>Una propiedad y una operación</h2><p>Una operación o método realiza una acción: <code>df.head()</code> solicita filas iniciales. Los paréntesis ejecutan esa acción. Un argumento dentro de ellos cambia lo que pedimos: <code>head(3)</code> solicita tres filas.</p><p>Una propiedad informa una característica que ya tiene el objeto: <code>df.shape</code> informa sus dimensiones. En esta propiedad no escribimos paréntesis. Cuando uses una instrucción por primera vez, revisa un ejemplo y su documentación.</p><p>Los corchetes después de una tabla permiten seleccionar información. Los corchetes que reúnen varios elementos crean una lista. La posición de esos signos determina su función; la selección de varias columnas se practica más adelante.</p>

### Comprobación

¿Qué instrucción pregunta si cantidad tiene el valor 100?

- cantidad = 100
- cantidad == 100
- "cantidad = 100"

<details><summary>Respuesta y razón</summary><p>cantidad == 100. = asigna. == compara. Una expresión completa entre comillas es texto y no realiza esa comparación.</p></details>

## pandas permite trabajar con tablas desde Python

Una biblioteca reúne herramientas que podemos utilizar sin escribir cada operación desde el principio.

Propósito: Importar pandas y explicar por qué lo llamamos pd.

<p><strong>pandas</strong> es una biblioteca de Python para manipular y analizar datos tabulares. Puede leer archivos, representar columnas y seleccionar registros, entre otras tareas. En esta clase practicaremos solo las operaciones de inspección y selección.</p><p>Una tabla de Excel y un DataFrame comparten filas y columnas. Excel permite editar celdas y fórmulas de forma interactiva. Con pandas escribimos instrucciones que se pueden ejecutar otra vez sobre un archivo. El DataFrame permanece en la memoria de Python; no guarda automáticamente los cambios en el CSV.</p><p>Para utilizar una biblioteca, primero la importamos. <code>pd</code> es un alias convencional: una forma corta de referirnos a pandas. No es el nombre de nuestros datos.</p>

### Poner las herramientas de pandas a disposición de Python.

El ejemplo empieza sin variables preparadas.

In [3]:
import pandas as pd

**Qué hace cada línea**

1. import solicita cargar una biblioteca. pandas es su nombre. as pd permite referirnos a ella con el alias pd.

**Resultado esperado:** La instrucción termina sin mostrar una tabla.

**Interpretación:** Importar no abre un CSV ni crea un DataFrame. Las operaciones siguientes usarán el prefijo pd.

**Error y corrección:** ModuleNotFoundError indica que la biblioteca no está instalada en el entorno. En este laboratorio, vuelve a activar Python; en un cuaderno revisa su instalación.

**Decisión:** Confirmar que la herramienta está disponible antes de iniciar la revisión de archivos.

<h2>Cómo ejecutarlo en tu propio cuaderno</h2><ol><li>Abre el cuaderno descargable de esta clase en Jupyter o Colab.</li><li>Selecciona la primera celda de código.</li><li>Ejecuta con Mayús más Intro.</li><li>Avanza de arriba abajo. Si reinicias el núcleo, vuelve a ejecutar las celdas que crean las variables.</li></ol><p>El núcleo o kernel es el proceso que conserva las variables mientras trabajas. Guardar un cuaderno conserva su texto; reiniciar el núcleo borra los objetos que tenía en memoria.</p>

### Comprobación

Después de ejecutar import pandas as pd, ¿qué representa pd?

- El archivo de producción
- Un alias para utilizar la biblioteca pandas
- La primera columna de la tabla

<details><summary>Respuesta y razón</summary><p>Un alias para utilizar la biblioteca pandas. pd es el alias de pandas. Para tener los datos todavía debemos crearlos o leerlos de un archivo.</p></details>

## Una Series representa una secuencia de valores con etiquetas

Primero observamos una sola variable. Después reuniremos varias en una tabla.

Propósito: Reconocer los valores y el índice de una Series.

<p>Una <strong>Series</strong> es un objeto de una dimensión. Reúne valores y un índice que permite identificarlos. Si no proporcionamos etiquetas, pandas utiliza normalmente 0, 1, 2 y así sucesivamente.</p><p>En el ejemplo trabajamos con tres cantidades. El índice de la primera posición será 0, pero el valor almacenado allí será 100. El cero no representa producción.</p>

### Organizar tres observaciones de cantidad para inspeccionarlas.

Preparación que necesita el ejemplo:

In [4]:
import pandas as pd

In [5]:
s = pd.Series([100, 110, 120])
s

0    100
1    110
2    120
dtype: int64

**Qué hace cada línea**

1. pd.Series construye una Series. Los corchetes contienen una lista de tres números y = guarda el objeto en s.

2. Escribir s como última expresión solicita que el cuaderno muestre su contenido.

**Resultado esperado:** Índice 0 con valor 100; índice 1 con 110; índice 2 con 120. El tipo es entero.

**Interpretación:** Hay tres observaciones de una variable. No hay todavía una columna de turno ni una fecha para cada una.

**Error y corrección:** NameError: pd indica que falta importar pandas o que se escribió otro alias. Ejecuta primero import pandas as pd.

**Decisión:** Verificar qué característica representa la secuencia y qué información falta para comparaciones de negocio.

<p><strong>Prueba:</strong> cambia únicamente el último valor de 120 a 125 y ejecuta otra vez. El índice seguirá siendo 2. La observación cambiará a 125 porque modificaste el contenido, no su etiqueta.</p><p>Una Series puede almacenar texto, cantidades o fechas. Su tipo depende de lo que contiene. En esta clase mantendremos un significado coherente por variable, para evitar mezclar unidades con categorías.</p>

### Comprobación

En la primera posición de la Series, el índice 0 indica…

- Una observación de cero unidades
- La etiqueta de la primera posición
- El costo del lote

<details><summary>Respuesta y razón</summary><p>La etiqueta de la primera posición. La etiqueta permite localizar el valor. La cantidad de esa posición es 100. El índice no es automáticamente un identificador de negocio.</p></details>

## Un DataFrame organiza registros en filas y columnas

Cada columna puede contener un tipo de dato diferente y cada fila reúne un registro.

Propósito: Construir una tabla pequeña y explicar de dónde sale cada fila.

<p>Un <strong>DataFrame</strong> es una estructura tabular de dos dimensiones. Los nombres de columna describen las variables y el índice etiqueta las filas. Al seleccionar una sola columna, obtenemos normalmente una Series.</p><p>Vamos a crear una tabla con turno y cantidad. El texto A y B identifica categorías. Los números 100 y 90 representan unidades. En esta construcción, los primeros elementos de las listas forman la primera fila.</p>

### Reunir dos variables para consultar registros completos.

Preparación que necesita el ejemplo:

In [6]:
import pandas as pd

In [7]:
mini = pd.DataFrame({
    "turno": ["A", "B"],
    "cantidad": [100, 90]
})
mini

  turno  cantidad
0     A       100
1     B        90

**Qué hace cada línea**

1. pd.DataFrame inicia la creación de una tabla. La llave abre un diccionario de nombres y valores.

2. "turno" es el nombre de la primera columna. Los dos puntos lo asocian con la lista ["A", "B"]. La coma separa esta columna de la siguiente.

3. "cantidad" se asocia con los números 100 y 90. Las dos listas tienen dos elementos.

4. La llave cierra el diccionario y el paréntesis cierra la construcción de DataFrame.

5. mini muestra el objeto guardado con ese nombre.

**Resultado esperado:** Dos filas y dos columnas: A con 100, B con 90.

**Interpretación:** La cantidad y el turno quedan en el mismo registro según su posición en las listas. Los nombres de columna describen qué significa cada valor.

**Error y corrección:** ValueError aparece si las listas tienen distintas longitudes. Antes de corregir, comprueba qué registro carece de un valor; no inventes una cantidad para igualarlas.

**Decisión:** Exigir que cada registro tenga los campos necesarios antes de incorporarlo a una tabla.

<h2>La etiqueta de pandas y el identificador del lote</h2><p>El índice automático 0 y 1 etiqueta las filas de esta tabla. En el archivo industrial, <code>id</code> identifica un lote del negocio. Aunque a veces coincidan, son conceptos diferentes. Más adelante verás que el filtro conserva los índices de origen.</p>

### Comprobación

¿Qué ocurre si turno tiene dos elementos y cantidad tiene tres?

- pandas completa automáticamente el turno faltante
- La construcción falla porque esas listas tienen distinta longitud
- Siempre se crea una tabla de seis filas

<details><summary>Respuesta y razón</summary><p>La construcción falla porque esas listas tienen distinta longitud. En esta construcción de DataFrame a partir de listas, sus longitudes deben coincidir. Se debe revisar el registro incompleto antes de decidir qué hacer.</p></details>

## El archivo conserva datos y read_csv los lleva a una tabla

CSV significa valores separados por comas. Su primera línea contiene aquí los nombres de las columnas.

Propósito: Distinguir el archivo guardado del DataFrame que pandas crea al leerlo.

<p>Un CSV es texto organizado en registros. En nuestro archivo una coma separa campos y cada línea corresponde a una fila. La primera línea contiene <code>id,fecha,producto,...</code>. Los decimales están escritos con punto para evitar confusión con el separador.</p><p>Puedes <a href="data/produccion.csv" download>descargar produccion.csv</a>. En el navegador, el laboratorio ya dispone de una copia con ese nombre. En Jupyter debes guardar el CSV junto al cuaderno, o indicar su ruta. En Colab puedes subirlo al panel de archivos; los archivos de una sesión pueden perderse al reiniciarla.</p>

### Abrir los registros de Taller Andino y comprobar que se leyó el archivo previsto.

El ejemplo empieza sin variables preparadas.

In [8]:
import pandas as pd
df = pd.read_csv("produccion.csv")
df.head()

   id       fecha producto linea  ... defectuosas  tiempo_min  parada_min  costo
0   1  2026-09-01       P1    L1  ...           2          60        22.5  70000
1   2  2026-09-02       P1    L1  ...           3          60        28.5  65000
2   3  2026-09-03       P1    L1  ...           4          60        19.5  75000
3   4  2026-09-04       P1    L1  ...           5          60        22.5  70000
4   5  2026-09-05       P1    L1  ...           2          60        13.5  80000

[5 rows x 10 columns]

**Qué hace cada línea**

1. Carga pandas con el alias pd.

2. pd.read_csv lee el archivo cuyo nombre es texto entre comillas. = guarda la tabla resultante en df.

3. head() muestra por defecto las primeras cinco filas.

**Resultado esperado:** Ids 1, 2, 3, 4 y 5; cantidades 100, 90, 110, 100 y 120.

**Interpretación:** El DataFrame ya está en memoria. El contenido del archivo y el objeto df son cosas distintas: editar el archivo no actualiza la tabla hasta leerlo otra vez.

**Error y corrección:** FileNotFoundError: revisa el nombre y la carpeta. Si toda la información queda en una sola columna, verifica el separador del archivo. Estos datos usan coma.

**Decisión:** Comprobar archivo, columnas y primeras filas antes de calcular indicadores.

<h2>Comprobación en tu computador</h2><ol><li>Ubica el CSV y el cuaderno en una misma carpeta.</li><li>Abre el cuaderno desde esa carpeta.</li><li>Ejecuta la importación y la lectura del CSV.</li><li>Comprueba que aparecen los primeros cinco ids del caso.</li></ol><p>Si el archivo tiene otro separador, <code>sep</code> permite declararlo. Aquí no hace falta cambiarlo. Tampoco es necesario guardar un Excel nuevo para que pandas pueda leer estos datos.</p>

### Comprobación

¿Qué contiene df después de la asignación?

- La ruta escrita como texto, sin abrir el archivo
- Un DataFrame con los datos que se leyeron
- Una copia automática de Excel con sus fórmulas

<details><summary>Respuesta y razón</summary><p>Un DataFrame con los datos que se leyeron. read_csv interpreta el contenido tabular y devuelve un DataFrame. El archivo original permanece guardado y no conserva fórmulas de Excel como tales.</p></details>

## Las primeras filas ayudan a comprobar la lectura, pero no describen todo el archivo

Combinamos una muestra visual con las dimensiones y los nombres de los campos.

Propósito: Utilizar head, tail, shape y columns sin confundir una vista parcial con el conjunto completo.

<p><code>head()</code> solicita las primeras filas y <code>tail()</code> las últimas. Sin argumento, cada método muestra hasta cinco. Estos métodos devuelven una vista de consulta: no recortan df de forma permanente.</p><p><code>shape</code> informa una pareja de números, primero filas y después columnas. <code>columns</code> informa sus nombres. Son propiedades y se consultan sin paréntesis.</p><p>Usa el explorador para cambiar qué filas se muestran. Observa que mostrar tres filas no cambia las ocho que tiene la tabla de origen.</p>

### Inspeccionar un inicio pequeño antes de revisar más campos.

Preparación que necesita el ejemplo:

In [9]:
import pandas as pd
df = pd.read_csv("produccion.csv")

In [10]:
df.head(3)

   id       fecha producto linea  ... defectuosas  tiempo_min  parada_min  costo
0   1  2026-09-01       P1    L1  ...           2          60        22.5  70000
1   2  2026-09-02       P1    L1  ...           3          60        28.5  65000
2   3  2026-09-03       P1    L1  ...           4          60        19.5  75000

[3 rows x 10 columns]

**Qué hace cada línea**

1. df es la tabla cargada en la preparación. El punto permite utilizar head y (3) solicita tres filas.

**Resultado esperado:** Ids 1, 2 y 3.

**Interpretación:** La vista contiene tres registros del inicio. La tabla df continúa teniendo ocho.

**Error y corrección:** Si escribes df.head sin paréntesis, puedes obtener la representación del método en vez de filas. Ejecuta head(3).

**Decisión:** Confirmar que los primeros registros corresponden al archivo esperado.

### Revisar los últimos registros del archivo.

Preparación que necesita el ejemplo:

In [11]:
import pandas as pd
df = pd.read_csv("produccion.csv")

In [12]:
df.tail(3)

   id       fecha producto linea  ... defectuosas  tiempo_min  parada_min  costo
5   6  2026-09-06       P1    L1  ...           3          60        19.5  75000
6   7  2026-09-07       P1    L1  ...           4          60         7.5  85000
7   8  2026-09-08       P1    L1  ...           5          60        13.5  80000

[3 rows x 10 columns]

**Qué hace cada línea**

1. tail(3) solicita las últimas tres filas de df.

**Resultado esperado:** Ids 6, 7 y 8, con cantidades 110, 130 y 120.

**Interpretación:** Un problema al final del archivo podría no verse al usar solo head.

**Error y corrección:** Confundir las etiquetas de índice con ids puede llevar a decir 5, 6 y 7. La columna id tiene 6, 7 y 8.

**Decisión:** Incluir registros del final al hacer una revisión inicial.

### Conocer la cobertura de registros y campos.

Preparación que necesita el ejemplo:

In [13]:
import pandas as pd
df = pd.read_csv("produccion.csv")

In [14]:
df.shape

(8, 10)

**Qué hace cada línea**

1. shape es una propiedad. El primer número es la cantidad de filas; el segundo es la cantidad de columnas.

**Resultado esperado:** (8, 10)

**Interpretación:** Hay ocho lotes registrados y diez variables. Ocho no es la producción acumulada.

**Error y corrección:** df.shape() provoca TypeError porque la pareja de valores no se ejecuta como una función. Retira los paréntesis.

**Decisión:** Comprobar si el número de lotes recibidos coincide con la entrega prevista.

### Consultar la escritura exacta de los nombres de columna.

Preparación que necesita el ejemplo:

In [15]:
import pandas as pd
df = pd.read_csv("produccion.csv")

In [16]:
df.columns

Index(['id', 'fecha', 'producto', 'linea', 'turno', 'cantidad', 'defectuosas',
       'tiempo_min', 'parada_min', 'costo'],
      dtype='str')

**Qué hace cada línea**

1. columns devuelve las etiquetas que permiten seleccionar los campos.

**Resultado esperado:** id, fecha, producto, linea, turno, cantidad, defectuosas, tiempo_min, parada_min y costo.

**Interpretación:** Los nombres se usan tal como aparecen, con sus letras y guiones bajos.

**Error y corrección:** Si eliges produccion como columna, aparecerá KeyError: este archivo usa cantidad. Revisa columns antes de seleccionar.

**Decisión:** Acordar nombres consistentes para las entregas futuras.

### Comprobación

Después de consultar df.head(3), ¿qué forma conserva df?

- (3, 10), porque head elimina el resto
- (8, 10), porque la consulta no modifica la tabla
- (10, 8), porque shape indica columnas y filas

<details><summary>Respuesta y razón</summary><p>(8, 10), porque la consulta no modifica la tabla. head devuelve las primeras filas para observarlas. No cambia df si no reasignas su resultado. shape presenta primero filas y después columnas.</p></details>

## Un número escrito como texto necesita una revisión distinta

pandas interpreta tipos al leer el archivo. Ese resultado debe compararse con el significado de cada variable.

Propósito: Reconocer cantidades numéricas, texto y presencia de valores antes de calcular.

<p>Un entero puede representar unidades producidas; un decimal puede representar minutos; una cadena de texto identifica un turno o un producto. <code>dtypes</code> permite revisar qué tipo se asignó a cada columna.</p><p>Las fechas del archivo están escritas con año, mes y día, pero inicialmente pandas las lee aquí como texto. El aspecto de una fecha no basta para que sea un objeto de fecha. La conversión se estudiará en la clase de preparación.</p><p><code>info()</code> imprime un resumen con dimensiones, nombres, tipos y cantidad de valores no nulos. Un valor no nulo está presente. Que esté presente no garantiza que sea correcto.</p>

### Comparar los tipos leídos con el diccionario del caso.

Preparación que necesita el ejemplo:

In [17]:
import pandas as pd
df = pd.read_csv("produccion.csv")

In [18]:
df.dtypes

id               int64
fecha              str
producto           str
linea              str
turno              str
cantidad         int64
defectuosas      int64
tiempo_min       int64
parada_min     float64
costo            int64
dtype: object

**Qué hace cada línea**

1. dtypes consulta el tipo de cada columna sin ejecutar un método.

**Resultado esperado:** id, cantidad, defectuosas, tiempo_min y costo son enteros. parada_min es decimal. fecha, producto, linea y turno son texto.

**Interpretación:** Las etiquetas exactas dependen de la versión: el texto puede aparecer como str u object. La diferencia de etiqueta no es por sí misma un error.

**Error y corrección:** Si cantidad aparece como texto, revisa qué valores tiene antes de hacer cálculos. Convertir sin revisar puede ocultar un formato incorrecto.

**Decisión:** Solicitar entregas con formatos coherentes con la variable.

### Revisar el resumen general y la presencia de datos.

Preparación que necesita el ejemplo:

In [19]:
import pandas as pd
df = pd.read_csv("produccion.csv")

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           8 non-null      int64
 1   fecha        8 non-null      str
 2   producto     8 non-null      str
 3   linea        8 non-null      str
 4   turno        8 non-null      str
 5   cantidad     8 non-null      int64
 6   defectuosas  8 non-null      int64
 7   tiempo_min   8 non-null      int64
 8   parada_min   8 non-null      float64
 9   costo        8 non-null      int64
dtypes: float64(1), int64(5), str(4)
memory usage: 772.0 bytes

**Qué hace cada línea**

1. info() imprime información de la tabla. No es necesario envolverlo en print para verla.

**Resultado esperado:** Ocho valores no nulos en cada una de las diez columnas.

**Interpretación:** Este archivo no contiene faltantes. Una tabla sin faltantes todavía podría tener duplicados o valores fuera de rango.

**Error y corrección:** Si escribes print(df.info()), puedes ver None al final: info ya imprimió el resumen y no devolvió otra tabla.

**Decisión:** Conservar esta revisión como punto de partida para una auditoría de calidad posterior.

<div class="notice"><strong>Un faltante y un cero tienen sentidos distintos</strong><p>Un cero de minutos puede registrar que no hubo parada. Un dato faltante expresa que no conocemos la medición. NaN es una representación habitual de un faltante numérico. En clases posteriores decidirás su tratamiento con una regla documentada.</p></div>

### Comprobación

info informa ocho valores no nulos en cantidad. ¿Qué permite concluir?

- Que las cantidades son correctas y representativas
- Que esa columna tiene un valor presente en cada uno de los ocho registros
- Que no hace falta revisar otras reglas de calidad

<details><summary>Respuesta y razón</summary><p>Que esa columna tiene un valor presente en cada uno de los ocho registros. No nulo describe presencia. La validez del número, su unidad y la cobertura de registros requieren otras comprobaciones.</p></details>

## La pregunta determina qué columnas necesitamos

Seleccionar una variable permite concentrarse en su contenido. Varias columnas mantienen el contexto de cada registro.

Propósito: Distinguir la selección de una Series de la selección de un DataFrame.

<p>Para consultar una columna, escribimos su nombre entre comillas dentro de los corchetes de df. El resultado es una Series. Para varias columnas, colocamos una lista de nombres dentro de esos corchetes.</p><p>En la segunda selección hay dos pares de corchetes con funciones diferentes. Los internos forman la lista <code>["turno", "cantidad"]</code>. Los externos le piden a df que seleccione esas columnas.</p>

### Consultar las cantidades de cada lote.

Preparación que necesita el ejemplo:

In [21]:
import pandas as pd
df = pd.read_csv("produccion.csv")

In [22]:
df["cantidad"]

0    100
1     90
2    110
3    100
4    120
5    110
6    130
7    120
Name: cantidad, dtype: int64

**Qué hace cada línea**

1. Los corchetes seleccionan la columna cuyo nombre es el texto "cantidad".

**Resultado esperado:** Series con 100, 90, 110, 100, 120, 110, 130 y 120.

**Interpretación:** Conservas una variable y las etiquetas de fila. No estás sumando ni cambiando las cantidades.

**Error y corrección:** KeyError: revisa las mayúsculas y que el nombre sea cantidad. Las columnas de pandas no se seleccionan con una etiqueta inventada.

**Decisión:** Revisar la variable que se necesita para una pregunta de volumen.

### Mantener juntos turno y cantidad al revisar lotes.

Preparación que necesita el ejemplo:

In [23]:
import pandas as pd
df = pd.read_csv("produccion.csv")

In [24]:
df[["turno", "cantidad"]]

  turno  cantidad
0     A       100
1     B        90
2     A       110
3     B       100
4     A       120
5     B       110
6     A       130
7     B       120

**Qué hace cada línea**

1. La lista interna enumera los dos nombres. Los corchetes externos hacen la selección sobre df.

**Resultado esperado:** DataFrame de ocho filas y dos columnas.

**Interpretación:** A y 100 quedan en el mismo registro de origen. La selección no cambia los datos del archivo.

**Error y corrección:** Si escribes df["turno", "cantidad"], pandas interpreta otra clase de etiqueta y normalmente genera KeyError. Usa una lista de nombres.

**Decisión:** Preparar una vista breve que conserve las variables necesarias para revisar turnos.

<h2>Una columna también puede conservarse como tabla</h2><p><code>df[["cantidad"]]</code> usa una lista de un nombre y devuelve un DataFrame de una columna. <code>df["cantidad"]</code> devuelve una Series. Los valores pueden coincidir, aunque el tipo de objeto sea diferente.</p>

### Comprobación

¿Cuál selección conserva un DataFrame con turno y cantidad?

- df["turno", "cantidad"]
- df[["turno", "cantidad"]]
- df[turno, cantidad]

<details><summary>Respuesta y razón</summary><p>df[[&quot;turno&quot;, &quot;cantidad&quot;]]. Los corchetes internos crean la lista de nombres. Los externos seleccionan esa lista en la tabla. Los nombres son texto y llevan comillas.</p></details>

## Un filtro conserva las filas que cumplen una condición

Primero hacemos una pregunta a cada registro y después seleccionamos los que responden True.

Propósito: Leer un filtro de adentro hacia afuera y comprobar las filas que conserva.

<p>La jefatura pregunta qué lotes corresponden al turno A. Podemos seleccionar la columna turno y comparar sus valores con el texto A. La comparación produce un valor booleano por fila.</p><p>Esos resultados forman una <strong>máscara</strong>: True conserva la fila y False la deja fuera del resultado. El filtro devuelve una tabla de consulta. No elimina los otros registros del archivo.</p>

### Identificar qué filas cumplen la condición antes de seleccionar.

Preparación que necesita el ejemplo:

In [25]:
import pandas as pd
df = pd.read_csv("produccion.csv")

In [26]:
df["turno"] == "A"

0     True
1    False
2     True
3    False
4     True
5    False
6     True
7    False
Name: turno, dtype: bool

**Qué hace cada línea**

1. Selecciona la columna turno y compara cada valor con el texto A. == compara y las comillas indican texto.

**Resultado esperado:** True en las posiciones de los ids 1, 3, 5 y 7. False en los otros cuatro.

**Interpretación:** El resultado todavía es una Series booleana. La condición se evaluó sobre cada registro.

**Error y corrección:** Escribir A sin comillas intenta usar una variable llamada A. Si no existe, aparece NameError.

**Decisión:** Comprobar que la condición representa la categoría que realmente se necesita.

### Conservar los lotes del turno A.

Preparación que necesita el ejemplo:

In [27]:
import pandas as pd
df = pd.read_csv("produccion.csv")

In [28]:
df[df["turno"] == "A"]

   id       fecha producto linea  ... defectuosas  tiempo_min  parada_min  costo
0   1  2026-09-01       P1    L1  ...           2          60        22.5  70000
2   3  2026-09-03       P1    L1  ...           4          60        19.5  75000
4   5  2026-09-05       P1    L1  ...           2          60        13.5  80000
6   7  2026-09-07       P1    L1  ...           4          60         7.5  85000

[4 rows x 10 columns]

**Qué hace cada línea**

1. El fragmento interno produce True o False por fila. Los corchetes externos seleccionan las filas donde el resultado es True.

**Resultado esperado:** Ids 1, 3, 5 y 7, con cantidades 100, 110, 120 y 130.

**Interpretación:** Hay cuatro lotes A. El filtro conserva sus índices originales, que pueden quedar separados; no es una falla de numeración.

**Error y corrección:** Una tabla vacía puede indicar que escribiste a minúscula en lugar de A, o que hay espacios en los datos. Revisa la categoría antes de concluir que no existen registros.

**Decisión:** Solicitar datos comparables del turno B antes de evaluar diferencias de desempeño.

### Localizar los lotes que alcanzaron al menos 120 unidades.

Preparación que necesita el ejemplo:

In [29]:
import pandas as pd
df = pd.read_csv("produccion.csv")

In [30]:
df[df["cantidad"] >= 120]

   id       fecha producto linea  ... defectuosas  tiempo_min  parada_min  costo
4   5  2026-09-05       P1    L1  ...           2          60        13.5  80000
6   7  2026-09-07       P1    L1  ...           4          60         7.5  85000
7   8  2026-09-08       P1    L1  ...           5          60        13.5  80000

[3 rows x 10 columns]

**Qué hace cada línea**

1. >= compara si cada cantidad es mayor o igual a 120. El número no lleva comillas. Los corchetes externos conservan las filas que cumplen.

**Resultado esperado:** Ids 5, 7 y 8: cantidades 120, 130 y 120.

**Interpretación:** El filtro incluye los dos lotes de exactamente 120. El umbral es didáctico, no una norma de productividad.

**Error y corrección:** Si usas > en lugar de >=, solo conservarás el id 7. Revisa si tu pregunta dice más de o al menos.

**Decisión:** Elegir qué lotes estudiar para conocer las condiciones de una cantidad elevada.

### Comprobación

Con la condición cantidad >= 120, ¿se conserva un lote de exactamente 120?

- Sí, porque >= incluye la igualdad
- No, porque solo admite cantidades mayores
- Depende del índice de la fila

<details><summary>Respuesta y razón</summary><p>Sí, porque &gt;= incluye la igualdad. El signo &gt;= significa mayor o igual. La condición &gt; 120 respondería una pregunta diferente.</p></details>

## Una inspección completa con comprobaciones pequeñas

Reúne lo aprendido y comprueba cada respuesta antes de pasar a la siguiente tarea.

Propósito: Inspeccionar el archivo desde cero y distinguir un hallazgo de una pregunta todavía pendiente.

<p>Trabaja con una pareja si es posible. Una persona escribe y otra predice la salida. Intercambien los roles después de revisar los tipos.</p><ol><li>Carga <code>produccion.csv</code> y muestra sus primeras filas.</li><li>Consulta dimensiones y nombres de columnas.</li><li>Revisa tipos y el resumen de valores presentes.</li><li>Selecciona cantidad como una sola variable.</li><li>Filtra los lotes A y compara sus ids con los registros originales.</li><li>Escribe qué sabes de la cobertura de estos datos.</li><li>Identifica una decisión que exigiría información adicional.</li></ol><p>En tu cuaderno debes ejecutar primero la importación y la lectura del archivo. En el laboratorio de esta página puedes ver esa preparación desplegando su explicación. Después de cada cambio, anticipa qué debería ocurrir.</p>

### Comprobar dimensiones como primer control de la práctica.

Preparación que necesita el ejemplo:

In [31]:
import pandas as pd
df = pd.read_csv("produccion.csv")

In [32]:
df.shape

(8, 10)

**Qué hace cada línea**

1. Consulta la pareja de filas y columnas. Puedes cambiar esta instrucción por otra de inspección que ya conozcas.

**Resultado esperado:** (8, 10)

**Interpretación:** La tabla describe ocho lotes y diez campos. Las siguientes comprobaciones ayudan a evitar confusiones con el índice.

**Error y corrección:** Si consultas otro archivo o editas los registros, las respuestas pueden cambiar. Esta práctica se corrige con el archivo original del caso.

**Decisión:** Verificar que el análisis comienza con una entrega reconocible.

<details><summary>Solución explicada de la práctica</summary><div><p><code>df.shape</code> devuelve (8, 10). <code>df.columns</code> enumera los diez campos del diccionario. <code>df.dtypes</code> identifica cantidades numéricas y texto. <code>df.info()</code> informa ocho valores presentes por columna.</p><p><code>df["cantidad"]</code> selecciona la variable como Series. <code>df[df["turno"] == "A"]</code> devuelve ids 1, 3, 5 y 7. Hay cuatro lotes por turno, un producto observado y una misma duración programada.</p><p>Podemos describir qué registró la empresa. Aún necesitamos más registros y condiciones comparables para atribuir diferencias a horarios, equipos o personas.</p></div></details>

## Un informe breve para revisar el turno B

Ahora cambian la pregunta y la selección. La explicación debe acompañar al resultado.

Propósito: Resolver una consulta por cuenta propia e interpretar su alcance.

<p>La jefatura solicita una vista de los <strong>lotes B</strong> que contenga únicamente su <strong>id y cantidad</strong>. Tu tarea es construir esa consulta y explicar qué decisión permite preparar.</p><ol><li>Predice cuántas filas tendrá el resultado.</li><li>Filtra el turno B y guarda el resultado con un nombre nuevo.</li><li>Selecciona id y cantidad de esa tabla.</li><li>Comprueba la salida y escribe qué información falta para evaluar desempeño.</li></ol><details><summary>Primera pista</summary><div><p>Ya conoces el filtro por A. Cambia solo la categoría de texto a B y guarda esa tabla en una variable, por ejemplo <code>turno_b</code>.</p></div></details><details><summary>Segunda pista</summary><div><p>Una variable que contiene un DataFrame permite usar la misma selección de columnas que df. Una lista de dos nombres conserva dos columnas.</p></div></details>

### Preparar una consulta que pueda revisar la jefatura.

Preparación que necesita el ejemplo:

In [33]:
import pandas as pd
df = pd.read_csv("produccion.csv")

In [34]:
turno_b = df[df["turno"] == "B"]
# Escribe aquí la selección de id y cantidad

**Qué hace cada línea**

1. La primera línea crea la tabla de los lotes B.

2. La segunda línea es un comentario: # indica que Python no la ejecuta. Sustituye ese comentario por tu selección.

**Resultado esperado:** Cuatro filas, dos columnas. Ids 2, 4, 6 y 8; cantidades 90, 100, 110 y 120.

**Interpretación:** La tabla resume los registros consultados. Por sí sola no permite atribuir las cantidades al turno ni al equipo.

**Error y corrección:** Si ejecutas únicamente la primera línea, Python guarda la tabla y puede no mostrarla. Escribe su nombre o la selección como última expresión.

**Decisión:** Solicitar una muestra más amplia con las mismas definiciones y condiciones del proceso antes de modificar recursos.

<details><summary>Solución para comparar después del intento</summary><div><pre class="code-display"><code>turno_b = df[df["turno"] == "B"]
turno_b[["id", "cantidad"]]</code></pre><p>La primera línea selecciona registros y los guarda. La segunda mantiene dos columnas sin sumar ni alterar cantidades. Los cuatro ids son 2, 4, 6 y 8. Una decisión razonable es revisar cobertura y recolectar más información comparable antes de explicar las diferencias.</p></div></details>

## Del archivo a un informe que se pueda revisar

Amplía la consulta inicial con controles y cálculos explicados. Realiza esta aplicación después de dominar los filtros.

Propósito: Construir un informe reproducible, distinguir producción de calidad y explicar el alcance de una comparación por turno.

<p>Taller Andino necesita un informe de sus ocho lotes. La pregunta es: ¿cuántas unidades se produjeron, cuántas fueron buenas y cómo se distribuyeron entre los turnos registrados? Tu entrega conservará los datos originales y explicará las operaciones.</p><div class="box yellow"><strong>Antes de comparar</strong><p>Los turnos A y B se registraron en fechas diferentes. Aunque los lotes tienen igual tiempo programado, desconocemos las condiciones de cada día. Una diferencia descriptiva exige estudiar posibles causas con más información.</p></div><h3>Paso 1. Comprueba si el archivo permite hacer las cuentas</h3><p>Empieza por las dimensiones y por los límites lógicos de las variables. Una cantidad negativa, defectuosas superiores a cantidad o una parada mayor que el tiempo programado impedirían interpretar directamente los indicadores. Un control que no encuentra problemas solo confirma las reglas que revisaste.</p>

### Revisar dimensiones, ausencias, ids repetidos y límites antes del cálculo.

Preparación que necesita el ejemplo:

In [35]:
import pandas as pd
df = pd.read_csv("produccion.csv")

In [36]:
print("Dimensiones:", df.shape)
print("Valores ausentes:", df.isna().sum().sum())
print("Ids repetidos:", df["id"].duplicated().sum())
invalido = (df["cantidad"] <= 0) | (df["defectuosas"] < 0) | (df["defectuosas"] > df["cantidad"]) | (df["parada_min"] < 0) | (df["parada_min"] > df["tiempo_min"])
df[invalido]

Dimensiones: (8, 10)
Valores ausentes: 0
Ids repetidos: 0

Empty DataFrame
Columns: [id, fecha, producto, linea, turno, cantidad, defectuosas, tiempo_min, parada_min, costo]
Index: []

**Qué hace cada línea**

1. shape devuelve ocho filas y diez columnas. print escribe la etiqueta y el resultado.

2. isna marca valores ausentes. El primer sum suma por columna y el segundo obtiene el total.

3. duplicated marca las apariciones repetidas de id después de la primera. sum cuenta esas marcas.

4. Cada comparación produce una máscara. | significa O entre máscaras; los paréntesis separan cada comparación.

5. df[invalido] muestra las filas donde al menos una regla falla.

**Resultado esperado:** Dimensiones (8, 10), cero valores ausentes, cero ids repetidos y una tabla vacía de registros inválidos.

**Interpretación:** El archivo cumple estos controles concretos. Aún debes confirmar qué mide cada campo y si la cobertura sirve para tu pregunta.

**Error y corrección:** Una tabla vacía es el resultado esperado de este control. No elimines registros automáticamente cuando una regla falle: consulta su origen.

**Decisión:** Detener el cálculo y documentar el problema si aparece un registro fuera de los límites.

### Calcular unidades buenas y minutos de operación sin escribir un ciclo.

Preparación que necesita el ejemplo:

In [37]:
import pandas as pd
df = pd.read_csv("produccion.csv")

In [38]:
df["buenas"] = df["cantidad"] - df["defectuosas"]
df["operacion_min"] = df["tiempo_min"] - df["parada_min"]
df[["id", "cantidad", "defectuosas", "buenas", "operacion_min"]]

   id  cantidad  defectuosas  buenas  operacion_min
0   1       100            2      98           37.5
1   2        90            3      87           31.5
2   3       110            4     106           40.5
3   4       100            5      95           37.5
4   5       120            2     118           46.5
5   6       110            3     107           40.5
6   7       130            4     126           52.5
7   8       120            5     115           46.5

**Qué hace cada línea**

1. Crea buenas restando defectuosas a cantidad en cada fila. La cantidad original incluye las defectuosas.

2. Crea operacion_min restando la parada al tiempo programado de cada lote.

3. La lista de cinco nombres selecciona las columnas que necesitas para comprobar la resta.

**Resultado esperado:** El lote 1 tiene 98 unidades buenas y 37.5 minutos de operación. El lote 8 tiene 115 buenas y 46.5 minutos.

**Interpretación:** La resta se aplica fila por fila. Los nuevos nombres quedan como columnas de la tabla de trabajo.

**Error y corrección:** No restes defectuosas de una cantidad que ya represente solo unidades buenas. Revisa la definición de la variable.

**Decisión:** Separar las unidades producidas de las aceptadas antes de calcular calidad.

### Reunir los lotes por turno y calcular la proporción de unidades buenas.

Preparación que necesita el ejemplo:

In [39]:
import pandas as pd
df = pd.read_csv("produccion.csv")
df["buenas"] = df["cantidad"] - df["defectuosas"]
df["operacion_min"] = df["tiempo_min"] - df["parada_min"]

In [40]:
resumen = df.groupby("turno")[["cantidad", "defectuosas", "buenas"]].sum()
resumen["calidad_pct"] = resumen["buenas"] / resumen["cantidad"] * 100
resumen.round(2)

       cantidad  defectuosas  buenas  calidad_pct
turno
A           460           12     448        97.39
B           420           16     404        96.19

**Qué hace cada línea**

1. groupby divide las filas según turno. La selección conserva tres cantidades y sum agrega sus valores dentro de cada grupo.

2. Divide la suma de buenas entre la suma de cantidad de cada turno y multiplica por 100.

3. round(2) muestra los resultados redondeados a dos decimales. No cambia la fórmula utilizada.

**Resultado esperado:** A: 460 producidas, 12 defectuosas, 448 buenas y 97.39 % de calidad. B: 420 producidas, 16 defectuosas, 404 buenas y 96.19 %.

**Interpretación:** La calidad agregada se calcula con sumas de unidades. Promediar los porcentajes de los lotes daría el mismo peso a lotes de tamaños diferentes.

**Error y corrección:** Este laboratorio prepara las columnas calculadas antes de agrupar. En tu cuaderno ejecuta el paso anterior primero.

**Decisión:** Solicitar registros comparables antes de atribuir la diferencia al turno.

### Guardar un resumen y volver a leerlo para comprobar su estructura.

Preparación que necesita el ejemplo:

In [41]:
import pandas as pd
df = pd.read_csv("produccion.csv")
df["buenas"] = df["cantidad"] - df["defectuosas"]
df["operacion_min"] = df["tiempo_min"] - df["parada_min"]

In [42]:
resumen = df.groupby("turno")[["cantidad", "defectuosas", "buenas"]].sum()
resumen["calidad_pct"] = resumen["buenas"] / resumen["cantidad"] * 100
resumen.reset_index().to_csv("resumen_turnos.csv", index=False)
print(pd.read_csv("resumen_turnos.csv").shape)

(2, 5)

**Qué hace cada línea**

1. Reúne las unidades por turno como en el paso anterior.

2. Añade la proporción de buenas expresada en porcentaje.

3. reset_index devuelve turno a una columna. to_csv escribe el archivo. index=False evita guardar un índice adicional.

4. Vuelve a leer el CSV y comprueba que tiene dos filas y cinco columnas.

**Resultado esperado:** (2, 5). El archivo se llama resumen_turnos.csv.

**Interpretación:** El archivo del resumen es un resultado distinto del archivo de origen. La lectura posterior comprueba sus dimensiones.

**Error y corrección:** En Colab descarga el CSV desde el panel Archivos antes de cerrar. Si usas Python en esta página, el archivo queda en su entorno temporal; conserva tu entrega desde Colab o Jupyter.

**Decisión:** Entregar un archivo que otra persona pueda abrir y revisar.

<h3>Paso 5. Redacta la interpretación</h3><p>El total del caso es de 880 unidades producidas, 28 defectuosas y 852 buenas. La calidad global es 852 / 880 × 100, aproximadamente 96.82 %. Estos resultados describen los registros disponibles.</p><details><summary>Ejemplo de informe breve para contrastar con el tuyo</summary><p>Se revisaron ocho lotes de la línea L1 y del producto P1. Los controles aplicados no detectaron ausencias, ids repetidos ni incumplimientos de los límites revisados. Se produjeron 880 unidades, de las cuales 852 fueron buenas. La calidad agregada fue 96.82 %. El turno A registró 460 unidades y el B, 420. Como corresponden a fechas diferentes, se requieren datos sobre condiciones de operación y más observaciones para estudiar las causas de la diferencia.</p></details><h3>Ejercicios de transferencia</h3><ol><li>Cambia el filtro para conservar solo los lotes con cinco unidades defectuosas. Predice sus ids antes de ejecutarlo.</li><li>Selecciona id, turno y defectuosas en ese resultado. Explica por qué debe conservar tres columnas.</li><li>Calcula el total de defectuosas del turno A sin copiar la tabla de resultados. Comprueba después si coincide con el resumen.</li><li>Explica por qué una calidad mayor puede coexistir con una cantidad producida menor en otro conjunto de datos.</li></ol><details><summary>Respuestas para revisar después del intento</summary><p>Los lotes con cinco defectuosas son 4 y 8. La selección conserva tres nombres porque la lista contiene id, turno y defectuosas. El turno A suma 12 defectuosas. La calidad es una proporción de unidades aceptadas y la cantidad es un conteo; cada medida responde una pregunta diferente.</p><pre class="code-display"><code>con_cinco = df[df["defectuosas"] == 5]
con_cinco[["id", "turno", "defectuosas"]]
df[df["turno"] == "A"]["defectuosas"].sum()</code></pre></details>

## Explora una selección y explica cómo cambian los indicadores

Compara tu predicción con los valores del caso. Cada filtro cambia el conjunto que estás describiendo.

Propósito: Calcular proporciones sobre las unidades seleccionadas y reconocer cuándo una consulta no devuelve lotes.

<p>Antes de usar los controles, anota una predicción. Selecciona A y pregunta cuánto debería sumar cantidad. Después aplica un mínimo de 120 y revisa cuáles lotes permanecen. Finalmente cambia la meta de calidad y explica por qué las unidades producidas permanecen iguales.</p>

<h3>Preguntas para discutir</h3><ol><li>¿Qué cambia en el denominador cuando filtras los registros?</li><li>Si ningún lote cumple el mínimo, ¿por qué no corresponde mostrar calidad de 0 %?</li><li>¿Una meta más exigente cambia las mediciones originales?</li><li>¿Qué contexto se pierde cuando se resume todo en un porcentaje?</li></ol><details><summary>Orientación para revisar tus respuestas</summary><p>El denominador es la suma de cantidad de los lotes que conserva la selección. Si no hay lotes, la proporción no se puede calcular. Cambiar una meta cambia la comparación con el resultado, pero deja iguales los datos observados. El porcentaje por sí solo no muestra fechas, tamaños de lote ni condiciones de operación.</p></details>

## Una entrega que otra persona pueda reproducir

Conserva los archivos y documenta la pregunta, las operaciones y el alcance de la respuesta.

Propósito: Entregar un cuaderno ejecutado con una interpretación que pueda contrastarse con los registros.

<h3>Qué entregar</h3><p>Conserva tu copia del cuaderno, el CSV de origen y el resumen por turno. Incluye una explicación breve con la pregunta, el significado de una fila, los controles realizados, la consulta y su resultado. Especifica qué información necesitarías antes de recomendar un cambio operativo.</p><h3>Revisión antes de entregar</h3><ol><li>Reinicia el entorno y ejecuta todas las celdas desde arriba. Corrige los errores que aparezcan.</li><li>Comprueba ocho filas y diez columnas al cargar el origen. Las columnas derivadas se añaden después.</li><li>Verifica los totales: 880 producidas, 28 defectuosas y 852 buenas.</li><li>Abre resumen_turnos.csv y confirma dos filas y cinco columnas, con turno incluido.</li><li>Revisa que tu interpretación describa los datos y reconozca la diferencia de fechas entre turnos.</li></ol><div class="table-wrap"><table><thead><tr><th>Criterio</th><th>Evidencia observable</th><th>Peso</th></tr></thead><tbody><tr><td>Datos y controles</td><td>Define la fila, conserva el origen y comprueba los límites.</td><td>25 %</td></tr><tr><td>Consultas y cálculos</td><td>Selecciona registros correctos y usa proporciones con denominador explicado.</td><td>30 %</td></tr><tr><td>Interpretación</td><td>Describe resultados sin atribuir causas que los registros no permiten comprobar.</td><td>30 %</td></tr><tr><td>Reproducción</td><td>El cuaderno se ejecuta en orden y el CSV se abre con la estructura prevista.</td><td>15 %</td></tr></tbody></table></div><p><a href="https://colab.research.google.com/github/karendayana2590-bot/analitica-de-datos-2.0/blob/main/cuadernos/Clase_1_pandas_desde_cero.ipynb" target="_blank" rel="noopener">Abrir el cuaderno para preparar la entrega</a>. Guardar mi trabajo en esta página descarga tus respuestas y código; la entrega del cuaderno se realiza por el medio que indique el docente.</p>

## Lo que puedes afirmar y lo que necesitas seguir investigando

Una buena revisión inicial identifica el contenido del archivo y también los límites de sus datos.

Propósito: Explicar con palabras propias qué hizo el código y qué alcance tienen sus resultados.

<p>El archivo tiene ocho lotes, diez campos, dos turnos y un producto observado. Puedes consultar su forma, revisar tipos y seleccionar registros. Esta revisión permite preparar preguntas de calidad y comparación para las clases siguientes.</p><p>Una conclusión inicial puede decir: «La tabla contiene cuatro lotes del turno A y cuatro del B, cada uno con 60 minutos programados. Las fechas se leyeron como texto. Antes de comparar el desempeño de los turnos, necesitamos revisar la cobertura y las condiciones de registro».</p><h2>Autoevaluación con explicación</h2><p>Responde las preguntas y revisa la razón de cada respuesta. Puedes volver a intentarlo. El resultado sirve para decidir qué repasar y no se envía al docente.</p>

<h2>Trabajo independiente de 120 minutos</h2><ol><li><strong>20 minutos:</strong> explica con un ejemplo fila, columna y variable.</li><li><strong>40 minutos:</strong> abre el cuaderno y repite las siete tareas de inspección sin mirar la solución.</li><li><strong>25 minutos:</strong> resuelve el reto del turno B y cambia después la pregunta a cantidad mayor o igual a 120.</li><li><strong>20 minutos:</strong> redacta dos hallazgos, una limitación y una acción razonable.</li><li><strong>15 minutos:</strong> reinicia el núcleo, ejecuta desde el principio y guarda el cuaderno y tus respuestas.</li></ol><details><summary>Resultados del trabajo independiente</summary><div><p>La tabla sigue siendo de ocho filas y diez columnas. El turno B devuelve ids 2, 4, 6 y 8. El filtro cantidad mayor o igual a 120 devuelve ids 5, 7 y 8. Si seleccionas id y cantidad sobre los lotes B, el resultado es de cuatro filas y dos columnas.</p><p>Un hallazgo es que cada lote registra la misma duración programada. Una limitación es la escasa cobertura de producto y tiempo. Una acción razonable es revisar consistencia y recolectar más lotes antes de cambiar decisiones operativas.</p></div></details><p>Guarda tu trabajo y comparte con el docente una explicación de la condición que utilizaste. Si una respuesta no coincide, revisa primero la pregunta y el archivo.</p>

## Solución ejecutable del reto después del intento

La primera línea conserva filas B en turno_b. La segunda usa una lista de dos nombres para conservar solo id y cantidad. El resultado debe tener ids 2, 4, 6 y 8, cantidades 90, 100, 110 y 120, y dos columnas.

In [43]:
import pandas as pd
df = pd.read_csv("produccion.csv")
turno_b = df[df["turno"] == "B"]
turno_b[["id", "cantidad"]]

   id  cantidad
1   2        90
3   4       100
5   6       110
7   8       120

## Explicación propia

Redacta qué representa una fila, cómo leíste el filtro y qué información necesitarías antes de comparar desempeño entre turnos. Tu explicación debe distinguir los ocho registros de las unidades producidas.

Antes de entregar, reinicia el núcleo y ejecuta desde la primera celda. Comprueba las mismas dimensiones y los mismos ids. Conserva el CSV y el cuaderno juntos si deseas repetir la lectura del archivo.